services:
  php:
    build: ./docker/php
    container_name: tbo-env-php
    volumes:
      - ./config/php/fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./src:/var/www/html
      - ./public:/root/public
      # SSH, GIT
      - /home/$USER/.ssh:/root/.ssh
      - /home/$USER/.gitconfig:/root/.gitconfig
      - /home/$USER/.git-credentials:/root/.git-credentials
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mysql
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
      - ./public:/root/public
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret

  web:
    image: nginx
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/sites:/etc/nginx/sites
      - ./config/nginx/certs:/etc/nginx/certs
      - ./config/nginx/logs:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
      - ./public:/root/public
    ports:
      - 80:80
      - 443:443
